language: node_js
node_js:
  - 10.11.0

cache:
  directories:
    - "node_modules"

env:
  global:
    - NODE_ENV=$APP_ENV

before_script:
  - npm install
  - npm link

script:
  - npm run build:prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  target-branch: gh-pages
  name: CI Deployment
  on:
    branch: develop
