version: 2

defaults: &defaults
  working_directory: ~/tmp
  docker:
    - image: circleci/node:10.11.0

  environment:
    NODE_ENV: ${APP_ENV}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Restore local dependencies from cache
      - restore_cache:
          keys: 
            - v1-dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Test the source code
      - run:
          name: Building
          command: npm run build:prod

      # Create and Save Artifact
      - run:
          name: Creating Artifacts
          command: |
            mkdir ./artifacts;
            zip -r ./artifacts/dist.zip dist/

      # Store Artifact
      - store_artifacts:
          path: ./artifacts/dist.zip

      - persist_to_workspace:
          root: ~/tmp
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp

      - add_ssh_keys:
          fingerprints: 
            - "16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48"

      # Configure gh-pages dependencies
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g --silent gh-pages
            git config user.email $GIT_EMAIL
            git config user.name "CircleCI"

      # Deploy to gh-pages
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --dotfiles --message "CI Deploy" --dist dist/

workflows:
  version: 2
  # Build and test
  build_flow:
    jobs:
      # Build application
      - build:
          filters:
            branches:
              only: develop
      
      # Publish to gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
